// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/entities/activity_entity.dart';
import 'src/entities/bookmark_entity.dart';
import 'src/entities/collection_entity.dart';
import 'src/entities/notification_entity.dart';
import 'src/entities/sync_cursor_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8542772984841996240),
    name: 'BookmarkEntity',
    lastPropertyId: const obx_int.IdUid(13, 1030815829066033616),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8567576389194229962),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6980862471056114681),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2996858872217884918),
        name: 'url',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5968208247687853418),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4634236816202482171),
        name: 'tags',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5176080626139921728),
        name: 'createdAt',
        type: 12,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5892767454409296107),
        name: 'updatedAt',
        type: 12,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2736399224269339936),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 1205513408758410617),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5777725754888659017),
        name: 'serverUpdatedAt',
        type: 12,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5606715827893123261),
        name: 'syncStateCode',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5870960339971504163),
        name: 'imageUrls',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 2425304307927444286),
        name: 'videoUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 1030815829066033616),
        name: 'rev',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 919939177363945290),
    name: 'ActivityEntity',
    lastPropertyId: const obx_int.IdUid(5, 3358862512730183168),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1252568795501351072),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8712645750653639276),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 4900372963106232767),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8458822913889059882),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8330749528174122264),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3358862512730183168),
        name: 'createdAt',
        type: 12,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 1349722681213321324),
    name: 'NotificationEntity',
    lastPropertyId: const obx_int.IdUid(8, 310238830684819705),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5623171801112591648),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3490771905479002669),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 7678540160299865532),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2530253008106623603),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4962516224363033753),
        name: 'body',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6903004669254115199),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3496464928661177200),
        name: 'isRead',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1877937495822827689),
        name: 'createdAt',
        type: 12,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 310238830684819705),
        name: 'pendingRead',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 6914250643421223724),
    name: 'CollectionEntity',
    lastPropertyId: const obx_int.IdUid(11, 2305123718041712993),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2023590956800309880),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2727045548820643396),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(4, 5110644076683273229),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7163441175278767034),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6568231165468057271),
        name: 'icon',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7202019221580211710),
        name: 'color',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8485286719118650298),
        name: 'bookmarkIds',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7311607500392150555),
        name: 'createdAt',
        type: 12,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7855977241027702413),
        name: 'updatedAt',
        type: 12,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2362733061684217003),
        name: 'serverUpdatedAt',
        type: 12,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5607791206085802444),
        name: 'syncStateCode',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2305123718041712993),
        name: 'rev',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 7251944359262926434),
    name: 'SyncCursorEntity',
    lastPropertyId: const obx_int.IdUid(3, 7189263519970957346),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4099947973977249183),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8892158510897589292),
        name: 'resource',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(5, 3983229944700575413),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7189263519970957346),
        name: 'rev',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(5, 7251944359262926434),
    lastIndexId: const obx_int.IdUid(5, 3983229944700575413),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    BookmarkEntity: obx_int.EntityDefinition<BookmarkEntity>(
      model: _entities[0],
      toOneRelations: (BookmarkEntity object) => [],
      toManyRelations: (BookmarkEntity object) => {},
      getId: (BookmarkEntity object) => object.id,
      setId: (BookmarkEntity object, int id) {
        object.id = id;
      },
      objectToFB: (BookmarkEntity object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final urlOffset = fbb.writeString(object.url);
        final descriptionOffset = fbb.writeString(object.description);
        final tagsOffset = fbb.writeList(
          object.tags.map(fbb.writeString).toList(growable: false),
        );
        final uuidOffset = fbb.writeString(object.uuid);
        final imageUrlsOffset = fbb.writeList(
          object.imageUrls.map(fbb.writeString).toList(growable: false),
        );
        final videoUrlOffset = object.videoUrl == null
            ? null
            : fbb.writeString(object.videoUrl!);
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, urlOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addOffset(4, tagsOffset);
        fbb.addInt64(5, object.createdAt.microsecondsSinceEpoch * 1000);
        fbb.addInt64(6, object.updatedAt.microsecondsSinceEpoch * 1000);
        fbb.addOffset(7, uuidOffset);
        fbb.addInt64(
          8,
          object.serverUpdatedAt == null
              ? null
              : object.serverUpdatedAt!.microsecondsSinceEpoch * 1000,
        );
        fbb.addInt64(9, object.syncStateCode);
        fbb.addOffset(10, imageUrlsOffset);
        fbb.addOffset(11, videoUrlOffset);
        fbb.addInt64(12, object.rev);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final serverUpdatedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final tagsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 12, []);
        final createdAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0) / 1000)
              .round(),
          isUtc: true,
        );
        final updatedAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0) / 1000)
              .round(),
          isUtc: true,
        );
        final serverUpdatedAtParam = serverUpdatedAtValue == null
            ? null
            : DateTime.fromMicrosecondsSinceEpoch(
                (serverUpdatedAtValue / 1000).round(),
                isUtc: true,
              );
        final syncStateCodeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final revParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final imageUrlsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 24, []);
        final videoUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final object = BookmarkEntity(
          id: idParam,
          uuid: uuidParam,
          title: titleParam,
          url: urlParam,
          description: descriptionParam,
          tags: tagsParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          serverUpdatedAt: serverUpdatedAtParam,
          syncStateCode: syncStateCodeParam,
          rev: revParam,
          imageUrls: imageUrlsParam,
          videoUrl: videoUrlParam,
        );

        return object;
      },
    ),
    ActivityEntity: obx_int.EntityDefinition<ActivityEntity>(
      model: _entities[1],
      toOneRelations: (ActivityEntity object) => [],
      toManyRelations: (ActivityEntity object) => {},
      getId: (ActivityEntity object) => object.id,
      setId: (ActivityEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ActivityEntity object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final descriptionOffset = fbb.writeString(object.description);
        final typeOffset = fbb.writeString(object.type);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addOffset(3, typeOffset);
        fbb.addInt64(4, object.createdAt.microsecondsSinceEpoch * 1000);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final createdAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0) / 1000)
              .round(),
          isUtc: true,
        );
        final object = ActivityEntity(
          id: idParam,
          uuid: uuidParam,
          description: descriptionParam,
          type: typeParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
    NotificationEntity: obx_int.EntityDefinition<NotificationEntity>(
      model: _entities[2],
      toOneRelations: (NotificationEntity object) => [],
      toManyRelations: (NotificationEntity object) => {},
      getId: (NotificationEntity object) => object.id,
      setId: (NotificationEntity object, int id) {
        object.id = id;
      },
      objectToFB: (NotificationEntity object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final titleOffset = fbb.writeString(object.title);
        final bodyOffset = fbb.writeString(object.body);
        final typeOffset = fbb.writeString(object.type);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, bodyOffset);
        fbb.addOffset(4, typeOffset);
        fbb.addBool(5, object.isRead);
        fbb.addInt64(6, object.createdAt.microsecondsSinceEpoch * 1000);
        fbb.addBool(7, object.pendingRead);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final bodyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final isReadParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final createdAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0) / 1000)
              .round(),
          isUtc: true,
        );
        final pendingReadParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final object = NotificationEntity(
          id: idParam,
          uuid: uuidParam,
          title: titleParam,
          body: bodyParam,
          type: typeParam,
          isRead: isReadParam,
          createdAt: createdAtParam,
          pendingRead: pendingReadParam,
        );

        return object;
      },
    ),
    CollectionEntity: obx_int.EntityDefinition<CollectionEntity>(
      model: _entities[3],
      toOneRelations: (CollectionEntity object) => [],
      toManyRelations: (CollectionEntity object) => {},
      getId: (CollectionEntity object) => object.id,
      setId: (CollectionEntity object, int id) {
        object.id = id;
      },
      objectToFB: (CollectionEntity object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final nameOffset = fbb.writeString(object.name);
        final iconOffset = fbb.writeString(object.icon);
        final bookmarkIdsOffset = fbb.writeList(
          object.bookmarkIds.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, iconOffset);
        fbb.addInt64(4, object.color);
        fbb.addOffset(5, bookmarkIdsOffset);
        fbb.addInt64(6, object.createdAt.microsecondsSinceEpoch * 1000);
        fbb.addInt64(7, object.updatedAt.microsecondsSinceEpoch * 1000);
        fbb.addInt64(
          8,
          object.serverUpdatedAt == null
              ? null
              : object.serverUpdatedAt!.microsecondsSinceEpoch * 1000,
        );
        fbb.addInt64(9, object.syncStateCode);
        fbb.addInt64(10, object.rev);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final serverUpdatedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final iconParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final colorParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final bookmarkIdsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 14, []);
        final createdAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0) / 1000)
              .round(),
          isUtc: true,
        );
        final updatedAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0) / 1000)
              .round(),
          isUtc: true,
        );
        final serverUpdatedAtParam = serverUpdatedAtValue == null
            ? null
            : DateTime.fromMicrosecondsSinceEpoch(
                (serverUpdatedAtValue / 1000).round(),
                isUtc: true,
              );
        final syncStateCodeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final revParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final object = CollectionEntity(
          id: idParam,
          uuid: uuidParam,
          name: nameParam,
          icon: iconParam,
          color: colorParam,
          bookmarkIds: bookmarkIdsParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          serverUpdatedAt: serverUpdatedAtParam,
          syncStateCode: syncStateCodeParam,
          rev: revParam,
        );

        return object;
      },
    ),
    SyncCursorEntity: obx_int.EntityDefinition<SyncCursorEntity>(
      model: _entities[4],
      toOneRelations: (SyncCursorEntity object) => [],
      toManyRelations: (SyncCursorEntity object) => {},
      getId: (SyncCursorEntity object) => object.id,
      setId: (SyncCursorEntity object, int id) {
        object.id = id;
      },
      objectToFB: (SyncCursorEntity object, fb.Builder fbb) {
        final resourceOffset = fbb.writeString(object.resource);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, resourceOffset);
        fbb.addInt64(2, object.rev);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final resourceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final revParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final object = SyncCursorEntity(
          resource: resourceParam,
          rev: revParam,
          id: idParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [BookmarkEntity] entity fields to define ObjectBox queries.
class BookmarkEntity_ {
  /// See [BookmarkEntity.id].
  static final id = obx.QueryIntegerProperty<BookmarkEntity>(
    _entities[0].properties[0],
  );

  /// See [BookmarkEntity.title].
  static final title = obx.QueryStringProperty<BookmarkEntity>(
    _entities[0].properties[1],
  );

  /// See [BookmarkEntity.url].
  static final url = obx.QueryStringProperty<BookmarkEntity>(
    _entities[0].properties[2],
  );

  /// See [BookmarkEntity.description].
  static final description = obx.QueryStringProperty<BookmarkEntity>(
    _entities[0].properties[3],
  );

  /// See [BookmarkEntity.tags].
  static final tags = obx.QueryStringVectorProperty<BookmarkEntity>(
    _entities[0].properties[4],
  );

  /// See [BookmarkEntity.createdAt].
  static final createdAt = obx.QueryDateNanoProperty<BookmarkEntity>(
    _entities[0].properties[5],
  );

  /// See [BookmarkEntity.updatedAt].
  static final updatedAt = obx.QueryDateNanoProperty<BookmarkEntity>(
    _entities[0].properties[6],
  );

  /// See [BookmarkEntity.uuid].
  static final uuid = obx.QueryStringProperty<BookmarkEntity>(
    _entities[0].properties[7],
  );

  /// See [BookmarkEntity.serverUpdatedAt].
  static final serverUpdatedAt = obx.QueryDateNanoProperty<BookmarkEntity>(
    _entities[0].properties[8],
  );

  /// See [BookmarkEntity.syncStateCode].
  static final syncStateCode = obx.QueryIntegerProperty<BookmarkEntity>(
    _entities[0].properties[9],
  );

  /// See [BookmarkEntity.imageUrls].
  static final imageUrls = obx.QueryStringVectorProperty<BookmarkEntity>(
    _entities[0].properties[10],
  );

  /// See [BookmarkEntity.videoUrl].
  static final videoUrl = obx.QueryStringProperty<BookmarkEntity>(
    _entities[0].properties[11],
  );

  /// See [BookmarkEntity.rev].
  static final rev = obx.QueryIntegerProperty<BookmarkEntity>(
    _entities[0].properties[12],
  );
}

/// [ActivityEntity] entity fields to define ObjectBox queries.
class ActivityEntity_ {
  /// See [ActivityEntity.id].
  static final id = obx.QueryIntegerProperty<ActivityEntity>(
    _entities[1].properties[0],
  );

  /// See [ActivityEntity.uuid].
  static final uuid = obx.QueryStringProperty<ActivityEntity>(
    _entities[1].properties[1],
  );

  /// See [ActivityEntity.description].
  static final description = obx.QueryStringProperty<ActivityEntity>(
    _entities[1].properties[2],
  );

  /// See [ActivityEntity.type].
  static final type = obx.QueryStringProperty<ActivityEntity>(
    _entities[1].properties[3],
  );

  /// See [ActivityEntity.createdAt].
  static final createdAt = obx.QueryDateNanoProperty<ActivityEntity>(
    _entities[1].properties[4],
  );
}

/// [NotificationEntity] entity fields to define ObjectBox queries.
class NotificationEntity_ {
  /// See [NotificationEntity.id].
  static final id = obx.QueryIntegerProperty<NotificationEntity>(
    _entities[2].properties[0],
  );

  /// See [NotificationEntity.uuid].
  static final uuid = obx.QueryStringProperty<NotificationEntity>(
    _entities[2].properties[1],
  );

  /// See [NotificationEntity.title].
  static final title = obx.QueryStringProperty<NotificationEntity>(
    _entities[2].properties[2],
  );

  /// See [NotificationEntity.body].
  static final body = obx.QueryStringProperty<NotificationEntity>(
    _entities[2].properties[3],
  );

  /// See [NotificationEntity.type].
  static final type = obx.QueryStringProperty<NotificationEntity>(
    _entities[2].properties[4],
  );

  /// See [NotificationEntity.isRead].
  static final isRead = obx.QueryBooleanProperty<NotificationEntity>(
    _entities[2].properties[5],
  );

  /// See [NotificationEntity.createdAt].
  static final createdAt = obx.QueryDateNanoProperty<NotificationEntity>(
    _entities[2].properties[6],
  );

  /// See [NotificationEntity.pendingRead].
  static final pendingRead = obx.QueryBooleanProperty<NotificationEntity>(
    _entities[2].properties[7],
  );
}

/// [CollectionEntity] entity fields to define ObjectBox queries.
class CollectionEntity_ {
  /// See [CollectionEntity.id].
  static final id = obx.QueryIntegerProperty<CollectionEntity>(
    _entities[3].properties[0],
  );

  /// See [CollectionEntity.uuid].
  static final uuid = obx.QueryStringProperty<CollectionEntity>(
    _entities[3].properties[1],
  );

  /// See [CollectionEntity.name].
  static final name = obx.QueryStringProperty<CollectionEntity>(
    _entities[3].properties[2],
  );

  /// See [CollectionEntity.icon].
  static final icon = obx.QueryStringProperty<CollectionEntity>(
    _entities[3].properties[3],
  );

  /// See [CollectionEntity.color].
  static final color = obx.QueryIntegerProperty<CollectionEntity>(
    _entities[3].properties[4],
  );

  /// See [CollectionEntity.bookmarkIds].
  static final bookmarkIds = obx.QueryStringVectorProperty<CollectionEntity>(
    _entities[3].properties[5],
  );

  /// See [CollectionEntity.createdAt].
  static final createdAt = obx.QueryDateNanoProperty<CollectionEntity>(
    _entities[3].properties[6],
  );

  /// See [CollectionEntity.updatedAt].
  static final updatedAt = obx.QueryDateNanoProperty<CollectionEntity>(
    _entities[3].properties[7],
  );

  /// See [CollectionEntity.serverUpdatedAt].
  static final serverUpdatedAt = obx.QueryDateNanoProperty<CollectionEntity>(
    _entities[3].properties[8],
  );

  /// See [CollectionEntity.syncStateCode].
  static final syncStateCode = obx.QueryIntegerProperty<CollectionEntity>(
    _entities[3].properties[9],
  );

  /// See [CollectionEntity.rev].
  static final rev = obx.QueryIntegerProperty<CollectionEntity>(
    _entities[3].properties[10],
  );
}

/// [SyncCursorEntity] entity fields to define ObjectBox queries.
class SyncCursorEntity_ {
  /// See [SyncCursorEntity.id].
  static final id = obx.QueryIntegerProperty<SyncCursorEntity>(
    _entities[4].properties[0],
  );

  /// See [SyncCursorEntity.resource].
  static final resource = obx.QueryStringProperty<SyncCursorEntity>(
    _entities[4].properties[1],
  );

  /// See [SyncCursorEntity.rev].
  static final rev = obx.QueryIntegerProperty<SyncCursorEntity>(
    _entities[4].properties[2],
  );
}
