// fst:feature:bookmarks:start
import 'package:feature_bookmarks/feature_bookmarks.dart';
// fst:feature:bookmarks:end
// fst:feature:collections:start
import 'package:feature_collections/feature_collections.dart';
// fst:feature:collections:end
// fst:feature:notifications:start
import 'package:feature_notifications/feature_notifications.dart';
// fst:feature:notifications:end
// fst:feature:_infra:start
import 'package:go_router/go_router.dart';
// fst:feature:_infra:end

// fst:feature:_infra:start
import 'di/injection.dart';
// fst:feature:_infra:end
import 'feature_module.dart';

/// All optional features enabled in this project.
///
/// Generated by `fst create` — edit to add or remove features.
const List<FeatureModule> enabledFeatures = [
  // fst:feature:bookmarks:start
  _BookmarksModule(),
  // fst:feature:bookmarks:end
  // fst:feature:collections:start
  _CollectionsModule(),
  // fst:feature:collections:end
  // fst:feature:notifications:start
  _NotificationsModule(),
  // fst:feature:notifications:end
  // fst:enabled-features — `fst add-feature` inserts new modules above this line
];

// fst:feature:bookmarks:start
final class _BookmarksModule extends FeatureModule {
  const _BookmarksModule();

  @override
  FeatureSyncController get syncController {
    final ctrl = getIt<BookmarksSyncController>();
    return _FeatureSync(onStart: ctrl.start, onStop: ctrl.stop);
  }

  @override
  Iterable<RouteBase> get routes => bookmarksRoutes;
}
// fst:feature:bookmarks:end

// fst:feature:collections:start
final class _CollectionsModule extends FeatureModule {
  const _CollectionsModule();

  @override
  FeatureSyncController get syncController {
    final ctrl = getIt<CollectionsSyncController>();
    return _FeatureSync(onStart: ctrl.start, onStop: ctrl.stop);
  }

  @override
  Iterable<RouteBase> get routes => collectionsRoutes;
}
// fst:feature:collections:end

// fst:feature:notifications:start
final class _NotificationsModule extends FeatureModule {
  const _NotificationsModule();

  @override
  FeatureSyncController get syncController {
    final ctrl = getIt<NotificationsSyncController>();
    return _FeatureSync(onStart: ctrl.start, onStop: ctrl.stop);
  }

  // Notifications' screen is mounted as a shell branch in router.dart, not via
  // enabledFeatures — so it contributes no app-level routes. The explicit empty
  // override also keeps go_router referenced when notifications is the only demo
  // feature left after `fst create --exclude-feature bookmarks,collections`.
  @override
  Iterable<RouteBase> get routes => const <RouteBase>[];
}
// fst:feature:notifications:end

// fst:feature-module-classes — `fst add-feature` inserts new module classes above

// fst:feature:_infra:start
/// Adapts any feature's sync controller to [FeatureSyncController] without a
/// bespoke wrapper class per feature. The controllers don't implement the
/// interface directly so feature packages stay unaware of the app's lifecycle.
final class _FeatureSync implements FeatureSyncController {
  const _FeatureSync({required this.onStart, required this.onStop});

  final Future<void> Function() onStart;
  final Future<void> Function() onStop;

  @override
  Future<void> start() => onStart();

  @override
  Future<void> stop() => onStop();
}

// fst:feature:_infra:end
